### ISSUE TITLE
错别字修正

### ISSUE THREAD

**Issue by akfuxin** [JDArmy/BREAK#3]
https://github.com/JDArmy/BREAK/blob/8c0898b01894fbb4f0616a02fab1d5f38c1ff19f/src/BREAK/risks/risks.json#L183

应该是经济损失

**Comment by Monyer** [comment]
感谢，已在 #[720a8a1](https://github.com/JDArmy/BREAK/commit/720a8a180c82fc85c00b699a958c37910d8202a5)修正。
