### ISSUE TITLE
恶意占库存这块建议再补充一些信息

### ISSUE THREAD

**Issue by we1h0** [JDArmy/BREAK#4]
通过恶意把商品加购物车的方式去探测商家的商品库存量

**Comment by we1h0** [comment]
或者新增一个新项，叫恶意加购物车，跟恶意占库存是一个类目。通过多个账号，恶意购买商品进入购物车，到支付阶段占用库存， 对多个库存账号占用的库存进行叠加，判断该商品库存数量。

**Comment by Monyer** [comment]
恶意加购物车与恶意下单都是进行恶意占库存的一种实现方式或手段，所以应不用再细分。不过的确如你所说，有些恶意占库存不是目标，而是手段，借此去获得库存数量，或者更经常见到的是获取商品的实际购买价格。此攻击手法描述已在https://break.jd.army/#/risk/R0014 #[e51810b](https://github.com/JDArmy/BREAK/commit/e51810b4e8ef1a3299128a32675e3014183fb01d) 增加补充说明！感谢提建议！
